apiVersion: apps/v1
kind: Deployment
metadata:
  name: amps-subscriber
spec:
  selector:
    matchLabels:
      app: amps-subscriber
  replicas: 1
  template:
    metadata:
      labels:
        app: amps-subscriber
    spec:
      containers:
      - name: amps-subscriber
        image: eu.gcr.io/deepak-cloud-work/amps-subscriber:1.0.0.16
        resources:
          requests:
            memory: 1000Mi
        env:
        - name: conUrl
          valueFrom:
            configMapKeyRef:
              name: amps-configmap
              key: conUrl
        - name: topic
          valueFrom:
            configMapKeyRef:
              name: amps-configmap
              key: topic

