apiVersion: apps/v1
kind: Deployment
metadata:
  name: amps-publisher
spec:
  selector:
    matchLabels:
      app: amps-publisher
  replicas: 5
  template:
    metadata:
      labels:
        app: amps-publisher
    spec:
      containers:
      - name: amps-publisher
        image: eu.gcr.io/deepak-cloud-work/amps-publisher:1.0.0.15
        resources:
          requests:
            memory: 1000Mi
        env:
        - name: conUrl
          valueFrom:
            configMapKeyRef:
              name: amps-configmap
              key: conUrl
        - name: topic
          valueFrom:
            configMapKeyRef:
              name: amps-configmap
              key: topic

