apiVersion: v1
kind: Service
metadata:
  name: amps-primary
  namespace: amps-namespace
spec:
  type: LoadBalancer
  ports:
    - name: tcp
      port: 8001
      targetPort: 8001
    - name: http
      port: 8199
      targetPort: 8199
  selector:
    statefulset.kubernetes.io/pod-name: amps-0