steps:
- name: gcr.io/cloud-builders/git
  entrypoint: /bin/bash
  args: ["-c", "echo ${_MAJOR}.${_MINOR}.${_PATCH}.$(cat amps/amps-server/version.txt) > IMAGE_TAG"]
- name: gradle:5.6.2-jdk8
  entrypoint: gradle
  args: ["-p", "amps/amps-components", "assemble"]
- name: gcr.io/cloud-builders/docker
  entrypoint: /bin/bash
  args: ["-c", "docker build -f amps/amps-components/DockerFilePublisher -t eu.gcr.io/$PROJECT_ID/amps-publisher:$(cat IMAGE_TAG) -t eu.gcr.io/$PROJECT_ID/amps-publisher:latest --cache-from eu.gcr.io/$PROJECT_ID/amps-publisher:latest --build-arg=JAR_FILE=build/libs/amps-components amps/amps-components/" ]
- name: gcr.io/cloud-builders/docker
  entrypoint: /bin/bash
  args: ["-c", "docker push eu.gcr.io/$PROJECT_ID/amps-publisher:$(cat IMAGE_TAG)"]
- name: gcr.io/cloud-builders/docker
  args: ["push", "eu.gcr.io/$PROJECT_ID/amps-publisher:latest"]
- name: gcr.io/cloud-builders/docker
  entrypoint: /bin/bash
  args: ["-c", "docker build -f amps/amps-components/DockerFileSubscriber -t eu.gcr.io/$PROJECT_ID/amps-subscriber:$(cat IMAGE_TAG) -t eu.gcr.io/$PROJECT_ID/amps-subscriber:latest --cache-from eu.gcr.io/$PROJECT_ID/amps-subscriber:latest --build-arg=JAR_FILE=build/libs/amps-components amps/amps-components/" ]
- name: gcr.io/cloud-builders/docker
  entrypoint: /bin/bash
  args: ["-c", "docker push eu.gcr.io/$PROJECT_ID/amps-subscriber:$(cat IMAGE_TAG)"]
- name: gcr.io/cloud-builders/docker
  args: ["push", "eu.gcr.io/$PROJECT_ID/amps-subscriber:latest"]
tags: ["my-ampsCompoents"]